spring:
  application:
    name: money-producer
  kafka:
    group-id: money-service
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
email:
  resource:
    url: http://localhost:8080/users
server:
  port: 8020